/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.tenasi.jdabot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Bot classUnderTest = new Bot();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
