/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.tenasi.jdabot;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import net.dv8tion.jda.api.JDA;

public class Bot {

    private final Logger log = LoggerFactory.getLogger(Bot.class);

    private final JDA jda;

    private final Set<AbstractHandler> handlers;

    private final Map<Class<? extends AbstractController>, AbstractController> controllers;

    public Bot(JDA jda) {
        this.jda = jda;
        this.handlers = new HashSet<>();
        this.controllers = new HashMap<>();
    }

}
